//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingLoad.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainingLoad.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Label_Activities {
            get {
                return ResourceManager.GetString("Label_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string Label_After {
            get {
                return ResourceManager.GetString("Label_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATL.
        /// </summary>
        internal static string Label_ATL {
            get {
                return ResourceManager.GetString("Label_ATL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Mode.
        /// </summary>
        internal static string Label_AutomaticMode {
            get {
                return ResourceManager.GetString("Label_AutomaticMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Label_Available {
            get {
                return ResourceManager.GetString("Label_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string Label_Before {
            get {
                return ResourceManager.GetString("Label_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        internal static string Label_BMI {
            get {
                return ResourceManager.GetString("Label_BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Details.
        /// </summary>
        internal static string Label_ChartDetails {
            get {
                return ResourceManager.GetString("Label_ChartDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTL.
        /// </summary>
        internal static string Label_CTL {
            get {
                return ResourceManager.GetString("Label_CTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTL/ATL.
        /// </summary>
        internal static string Label_CTLATL {
            get {
                return ResourceManager.GetString("Label_CTLATL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Training Status.
        /// </summary>
        internal static string Label_CurrentTrainingStatus {
            get {
                return ResourceManager.GetString("Label_CurrentTrainingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Fields.
        /// </summary>
        internal static string Label_CustomFields {
            get {
                return ResourceManager.GetString("Label_CustomFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        internal static string Label_Cycle {
            get {
                return ResourceManager.GetString("Label_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daniels Points.
        /// </summary>
        internal static string Label_DanielsPoints {
            get {
                return ResourceManager.GetString("Label_DanielsPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Label_Days {
            get {
                return ResourceManager.GetString("Label_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Chart Zoom (days).
        /// </summary>
        internal static string Label_DefaultChartZoom {
            get {
                return ResourceManager.GetString("Label_DefaultChartZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Zone Factors.
        /// </summary>
        internal static string Label_DynamicZones {
            get {
                return ResourceManager.GetString("Label_DynamicZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic.
        /// </summary>
        internal static string Label_Epic {
            get {
                return ResourceManager.GetString("Label_Epic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string Label_Factor {
            get {
                return ResourceManager.GetString("Label_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatigue.
        /// </summary>
        internal static string Label_Fatigue {
            get {
                return ResourceManager.GetString("Label_Fatigue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Charts.
        /// </summary>
        internal static string Label_FilterCharts {
            get {
                return ResourceManager.GetString("Label_FilterCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        internal static string Label_Fitness {
            get {
                return ResourceManager.GetString("Label_Fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast CTL/ATL/TSB.
        /// </summary>
        internal static string Label_ForecastCTLATLTSB {
            get {
                return ResourceManager.GetString("Label_ForecastCTLATLTSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP {0}.
        /// </summary>
        internal static string Label_FTP {
            get {
                return ResourceManager.GetString("Label_FTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Threshold Power.
        /// </summary>
        internal static string Label_FunctionalThresholdPower {
            get {
                return ResourceManager.GetString("Label_FunctionalThresholdPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future.
        /// </summary>
        internal static string Label_Future {
            get {
                return ResourceManager.GetString("Label_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string Label_High {
            get {
                return ResourceManager.GetString("Label_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Zones.
        /// </summary>
        internal static string Label_HRZones {
            get {
                return ResourceManager.GetString("Label_HRZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial ATL.
        /// </summary>
        internal static string Label_InitialATL {
            get {
                return ResourceManager.GetString("Label_InitialATL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial CTL.
        /// </summary>
        internal static string Label_InitialCTL {
            get {
                return ResourceManager.GetString("Label_InitialCTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity Factor.
        /// </summary>
        internal static string Label_IntensityFactor {
            get {
                return ResourceManager.GetString("Label_IntensityFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Settings.
        /// </summary>
        internal static string Label_ListSettings {
            get {
                return ResourceManager.GetString("Label_ListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Label_Low {
            get {
                return ResourceManager.GetString("Label_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Training Effect.
        /// </summary>
        internal static string Label_MaxTrainingEffect {
            get {
                return ResourceManager.GetString("Label_MaxTrainingEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Label_Medium {
            get {
                return ResourceManager.GetString("Label_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multisport.
        /// </summary>
        internal static string Label_MultiSport {
            get {
                return ResourceManager.GetString("Label_MultiSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norm. Power.
        /// </summary>
        internal static string Label_NormPower {
            get {
                return ResourceManager.GetString("Label_NormPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Label_Options {
            get {
                return ResourceManager.GetString("Label_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        internal static string Label_Past {
            get {
                return ResourceManager.GetString("Label_Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string Label_Perf {
            get {
                return ResourceManager.GetString("Label_Perf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        internal static string Label_Recalculate {
            get {
                return ResourceManager.GetString("Label_Recalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default....
        /// </summary>
        internal static string Label_Reset {
            get {
                return ResourceManager.GetString("Label_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Category.
        /// </summary>
        internal static string Label_ResetCategory {
            get {
                return ResourceManager.GetString("Label_ResetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Sum.
        /// </summary>
        internal static string Label_RollingSum {
            get {
                return ResourceManager.GetString("Label_RollingSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Label_Run {
            get {
                return ResourceManager.GetString("Label_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Charts.
        /// </summary>
        internal static string Label_SelectedCharts {
            get {
                return ResourceManager.GetString("Label_SelectedCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Columns.
        /// </summary>
        internal static string Label_SelectedColumns {
            get {
                return ResourceManager.GetString("Label_SelectedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Target Date.
        /// </summary>
        internal static string Label_SetTargetDate {
            get {
                return ResourceManager.GetString("Label_SetTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Label_Settings {
            get {
                return ResourceManager.GetString("Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Zone.
        /// </summary>
        internal static string Label_SingleZone {
            get {
                return ResourceManager.GetString("Label_SingleZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swim.
        /// </summary>
        internal static string Label_Swim {
            get {
                return ResourceManager.GetString("Label_Swim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taper Date.
        /// </summary>
        internal static string Label_TaperDate {
            get {
                return ResourceManager.GetString("Label_TaperDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        internal static string Label_TargetDate {
            get {
                return ResourceManager.GetString("Label_TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Constants.
        /// </summary>
        internal static string Label_TimeConstants {
            get {
                return ResourceManager.GetString("Label_TimeConstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Influence.
        /// </summary>
        internal static string Label_TrainingInfluence {
            get {
                return ResourceManager.GetString("Label_TrainingInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Load.
        /// </summary>
        internal static string Label_TrainingLoad {
            get {
                return ResourceManager.GetString("Label_TrainingLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Load Chart.
        /// </summary>
        internal static string Label_TrainingLoadChart {
            get {
                return ResourceManager.GetString("Label_TrainingLoadChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Stress Balance.
        /// </summary>
        internal static string Label_TrainingStressBalance {
            get {
                return ResourceManager.GetString("Label_TrainingStressBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Stress Score.
        /// </summary>
        internal static string Label_TrainingStressScore {
            get {
                return ResourceManager.GetString("Label_TrainingStressScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIMP.
        /// </summary>
        internal static string Label_TRIMP {
            get {
                return ResourceManager.GetString("Label_TRIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSB.
        /// </summary>
        internal static string Label_TSB {
            get {
                return ResourceManager.GetString("Label_TSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSS.
        /// </summary>
        internal static string Label_TSS {
            get {
                return ResourceManager.GetString("Label_TSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Load is about to migrate your FTP settings to the new ST3 custom fields.
        ///This will move the entries from &apos;{0}&apos; athlete data to a new &apos;FTPcycling&apos; custom parameter.
        ///Training Load will not ask you again once your logbook is saved.  Click OK to continue migration, or Cancel to skip it and not migrate your data..
        /// </summary>
        internal static string Text_MigrationAnnouncement {
            get {
                return ResourceManager.GetString("Text_MigrationAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acute Training Load.
        /// </summary>
        internal static string ToolTip_ATL {
            get {
                return ResourceManager.GetString("ToolTip_ATL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic Training Load.
        /// </summary>
        internal static string ToolTip_CTL {
            get {
                return ResourceManager.GetString("ToolTip_CTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked: Use static HR zone factors defined here on the settings page.  
        ///
        ///Checked: Use calculated zone factors based on HRmax &amp;amp; HRrest 
        ///at the time of the activity.  This will consider changes in HRrest 
        ///and HRmax over time..
        /// </summary>
        internal static string ToolTip_DynamicZones {
            get {
                return ResourceManager.GetString("ToolTip_DynamicZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked: CTL &amp; ATL data will also be filtered with the category filter.
        ///Unchecked: Only the activities list will be filtered..
        /// </summary>
        internal static string ToolTip_FilterCharts {
            get {
                return ResourceManager.GetString("ToolTip_FilterCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend CTL, ATL, &amp; TSB 7 days past TSB peak..
        /// </summary>
        internal static string ToolTip_Forecast {
            get {
                return ResourceManager.GetString("ToolTip_Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting point for ATL moving average.
        /// </summary>
        internal static string ToolTip_InitialATL {
            get {
                return ResourceManager.GetString("ToolTip_InitialATL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting point for CTL moving average.
        /// </summary>
        internal static string ToolTip_InitialCTL {
            get {
                return ResourceManager.GetString("ToolTip_InitialCTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset HR zone factors to default..
        /// </summary>
        internal static string ToolTip_ResetCategory {
            get {
                return ResourceManager.GetString("ToolTip_ResetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in &apos;Rolling Sum&apos; charts.
        /// </summary>
        internal static string ToolTip_RollingSum {
            get {
                return ResourceManager.GetString("ToolTip_RollingSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked: All TRIMP calcs will use a single HR zone (such as a custom TRIMP HR zone).  
        ///Unchecked: Calcs use activity category &amp; factors..
        /// </summary>
        internal static string ToolTip_SingleZone {
            get {
                return ResourceManager.GetString("ToolTip_SingleZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The single heart rate zone to use for all activity TRIMP calculations..
        /// </summary>
        internal static string ToolTip_SingleZone2 {
            get {
                return ResourceManager.GetString("ToolTip_SingleZone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATL: Acute Training Load
        ///Similar to a short term moving average of your TrImp scores. 
        ///The recommended time constant setting is around 10-15 days.
        ///
        ///ATL is often referred to as your &apos;fatigue&apos;. As you train, you need
        ///to recover. A high ATL indicates a lot of recent training, and may 
        ///indicate a need for some recovery..
        /// </summary>
        internal static string ToolTip_TCa {
            get {
                return ResourceManager.GetString("ToolTip_TCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTL: Chronic Training Load
        ///Calculated as something similar to a long term moving average of your TrImp scores. 
        ///The recommended time constant for this is around 45 days. 
        ///
        ///CTL is often referred to as your &apos;fitness&apos;. You have to work harder and longer to move 
        ///your CTL, because it moves slower, but as it creeps up, it represents your improved 
        ///conditioning..
        /// </summary>
        internal static string ToolTip_TCc {
            get {
                return ResourceManager.GetString("ToolTip_TCc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
